// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Option is a selectable item (model, language, or voice).
 */
export interface Option {
    "id": string;
    "name": string;
}
