// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../livingspeech/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "speech:chunk": main$0.SpeechChunk;
            "speech:done": main$0.SpeechEnd;
            "speech:progress": main$0.SpeechProgress;
        }
    }
}
