// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as SpeechService from "./speechservice.js";
export {
    SpeechService
};

export type {
    SpeechChunk,
    SpeechEnd,
    Status
} from "./models.js";
