// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * Event payloads sent to the frontend. ID identifies the utterance so the
 * frontend can ignore chunks from a request it has already stopped.
 */
export interface SpeechChunk {
    "id": number;

    /**
     * base64 WAV
     */
    "audio": string;
}

export interface SpeechEnd {
    "id": number;
    "error"?: string;
}

/**
 * Status describes whether OpenVox is reachable and which voice will be used.
 */
export interface Status {
    "reachable": boolean;
    "error"?: string;
    "settings": store$0.Settings;
}
