// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SpeechService is bound to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as openvox$0 from "./internal/openvox/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(3971361796);
}

export function HidePanel(): $CancellablePromise<void> {
    return $Call.ByID(289053783);
}

export function ListLanguages(model: string): $CancellablePromise<openvox$0.Option[] | null> {
    return $Call.ByID(2410829198, model);
}

export function ListModels(): $CancellablePromise<openvox$0.Option[] | null> {
    return $Call.ByID(2133093653);
}

export function ListVoices(model: string, language: string): $CancellablePromise<openvox$0.Option[] | null> {
    return $Call.ByID(3972379224, model, language);
}

/**
 * Preview speaks a sample sentence with the current settings.
 */
export function Preview(): $CancellablePromise<number> {
    return $Call.ByID(568302537);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(3028652712);
}

export function Recent(): $CancellablePromise<store$0.RecentEntry[] | null> {
    return $Call.ByID(2261980748);
}

/**
 * SaveSettings stores the selection and warms the model if it changed.
 */
export function SaveSettings(s: store$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(80780047, s);
}

/**
 * ScreenHeight returns the height of the screen the panel is on, in points.
 */
export function ScreenHeight(): $CancellablePromise<number> {
    return $Call.ByID(1693358684);
}

export function ServerURL(): $CancellablePromise<string> {
    return $Call.ByID(3112920301);
}

/**
 * SetPanelHeight resizes the panel to fit its content, keeping its top edge in place.
 */
export function SetPanelHeight(height: number): $CancellablePromise<void> {
    return $Call.ByID(532468258, height);
}

/**
 * Speak starts speaking text and records it in the recent list. Audio arrives
 * via speech:chunk events; speech:done fires at the end. Returns the utterance ID.
 */
export function Speak(text: string): $CancellablePromise<number> {
    return $Call.ByID(4180837055, text);
}

/**
 * Status checks the server and returns the effective settings.
 */
export function Status(): $CancellablePromise<$models.Status> {
    return $Call.ByID(3437190377);
}

/**
 * StopSpeaking cancels any in-flight generation.
 */
export function StopSpeaking(): $CancellablePromise<void> {
    return $Call.ByID(3051209233);
}
