// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SpeechService is bound to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as openvox$0 from "./internal/openvox/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetLaunchAtLogin reports whether LivingSpeech opens at login.
 */
export function GetLaunchAtLogin(): $CancellablePromise<$models.LaunchAtLogin> {
    return $Call.ByID(909659052);
}

export function GetSettings(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(3971361796);
}

export function HidePanel(): $CancellablePromise<void> {
    return $Call.ByID(289053783);
}

export function ListLanguages(model: string): $CancellablePromise<openvox$0.Option[] | null> {
    return $Call.ByID(2410829198, model);
}

export function ListModels(): $CancellablePromise<openvox$0.Option[] | null> {
    return $Call.ByID(2133093653);
}

export function ListVoices(model: string, language: string): $CancellablePromise<openvox$0.Option[] | null> {
    return $Call.ByID(3972379224, model, language);
}

/**
 * OpenLoginItemsSettings opens System Settings › General › Login Items.
 */
export function OpenLoginItemsSettings(): $CancellablePromise<void> {
    return $Call.ByID(510629385);
}

/**
 * OpenSpokenContentSettings opens System Settings where the System Voice is chosen.
 */
export function OpenSpokenContentSettings(): $CancellablePromise<void> {
    return $Call.ByID(2719447267);
}

/**
 * Preview speaks a sample sentence with the current settings.
 */
export function Preview(): $CancellablePromise<number> {
    return $Call.ByID(568302537);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(3028652712);
}

export function Recent(): $CancellablePromise<store$0.RecentEntry[] | null> {
    return $Call.ByID(2261980748);
}

/**
 * SaveSettings stores the selection and warms the model if it changed.
 */
export function SaveSettings(s: store$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(80780047, s);
}

/**
 * ScreenHeight returns the height of the screen the panel is on, in points.
 */
export function ScreenHeight(): $CancellablePromise<number> {
    return $Call.ByID(1693358684);
}

export function ServerURL(): $CancellablePromise<string> {
    return $Call.ByID(3112920301);
}

/**
 * SetLaunchAtLogin turns opening at login on or off and returns the new state.
 */
export function SetLaunchAtLogin(on: boolean): $CancellablePromise<$models.LaunchAtLogin> {
    return $Call.ByID(2648237584, on);
}

/**
 * SetPanelSize resizes the panel to fit its content, keeping its top-left corner in place.
 */
export function SetPanelSize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(2202622268, width, height);
}

/**
 * Speak starts speaking text and records it in the recent list. Audio arrives
 * via speech:chunk events; speech:done fires at the end. Returns the utterance ID.
 */
export function Speak(text: string): $CancellablePromise<number> {
    return $Call.ByID(4180837055, text);
}

/**
 * Status returns the effective settings and, for OpenVox, whether it's reachable.
 */
export function Status(): $CancellablePromise<$models.Status> {
    return $Call.ByID(3437190377);
}

/**
 * StopSpeaking cancels any in-flight generation.
 */
export function StopSpeaking(): $CancellablePromise<void> {
    return $Call.ByID(3051209233);
}
