// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecentEntry is a phrase that was spoken.
 */
export interface RecentEntry {
    "text": string;
    "at": string;
}

/**
 * Settings holds the user's voice selection.
 */
export interface Settings {
    "model": string;
    "language": string;
    "voice": string;
    "baseURL"?: string;
}
