// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecentEntry is a phrase that was spoken.
 */
export interface RecentEntry {
    "text": string;
    "at": string;
}

/**
 * Settings holds the user's voice selection.
 */
export interface Settings {
    /**
     * Engine is EngineSystem or EngineOpenVox; empty means EngineSystem.
     */
    "engine"?: string;
    "model": string;
    "language": string;
    "voice": string;

    /**
     * FontSize is the UI's base font size in points; 0 means the default.
     */
    "fontSize"?: number;
    "baseURL"?: string;
}
